run: build-wasm
    wasmtime -Wgc --dir .::.  build/2017.wasm

debug: build-wasm
    node --inspect-brk node-run.js

build-wat: compiler
    mkdir -p build
    guile -c '(load-compiled "build/mwatc.go")' day-*/*.mwat main.mwat stdlib/*.mwat

build-wasm: build-wat
    wasm-tools parse -g build/2017.wat -o build/2017.wasm

compiler:
    guild compile -o build/mwatc.go compiler/mwatc.scm
