run: build-wasm
    wasmtime --dir .::.  build/2017.wasm

debug: build-wasm
    node --inspect-brk node-run.js

build-wat: compiler
    mkdir -p build
    guile -c '(load-compiled "build/mwatc.go")' day-*/*.mwat 2017.mwat
    cat build/2017.wit

build-wasm: build-wat
    # wasm-tools component targets build/2017.wit build/2017.wat
    # wasm-tools component embed build/2017.wit build/2017.wat -o build/2017.wasm
    # wat2wasm build/2017.wat --enable-all --debug-names -o build/2017.wasm
    wasm-tools parse build/2017.wat -o build/2017.wasm

compiler:
    guild compile -o build/mwatc.go compiler/mwatc.scm
